# Generated by Django 3.1.1 on 2020-10-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='Day Of The Event', verbose_name='Day Of The Event')),
                ('start_time', models.TimeField(help_text='Starting Time', verbose_name='Starting Time')),
                ('end_time', models.TimeField(help_text='Final Time', verbose_name='Final Time')),
                ('notes', models.TextField(blank=True, help_text='Textual Notes', null=True, verbose_name='Textual Notes')),
            ],
            options={
                'verbose_name': 'Scheduling',
                'verbose_name_plural': 'Scheduling',
            },
        ),
    ]
