# Generated by Django 3.1.1 on 2020-11-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='hours_clocked',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
