# Generated by Django 3.1.1 on 2020-11-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_trainer_wages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='wages',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
