# Generated by Django 3.1.1 on 2020-10-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20201030_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(help_text='Final Time', null=True, verbose_name='Final Time'),
        ),
    ]
