# Generated by Django 3.1.1 on 2020-11-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_trainer_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='repititions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
